const BASE={openingCash:-144853,existingCapacity:192000,existingMaintenance:4700,existingDepreciation:16250,milkCost:20000,milkOutput:20000,salary:10000,salePrice:2,taxRate:.10};
const premises={A:{rent:12000,transport:.3,slots:1},B:{rent:10000,transport:.4,slots:1},C:{rent:12000,transport:.3,slots:1},D:{rent:17000,transport:.1,slots:1},E:{rent:15000,transport:.2,slots:2},F:{rent:16000,transport:.2,slots:3}};
const machines={none:{name:'No new machine',capacity:0,purchase:0,maintenance:0,depreciation:0},3:{name:'Machine 3',capacity:68000,purchase:38000,maintenance:2100,depreciation:4750},4:{name:'Machine 4',capacity:95000,purchase:70000,maintenance:2900,depreciation:8750},5:{name:'Machine 5',capacity:45000,purchase:28000,maintenance:1300,depreciation:3500},6:{name:'Machine 6',capacity:110000,purchase:90000,maintenance:2900,depreciation:11250}};
const defaults={a:{forecast:320000,request:150000,allocation:120000,market:5000,milk:7,premise:'B',machine:'none',loan:180000,term:4,production:140000},b:{forecast:360000,request:200000,allocation:170000,market:15000,milk:10,premise:'D',machine:'4',loan:250000,term:6,production:200000}};
const fieldDefs=[
 ['forecast','Forecast market size','number','units'],['request','Requested sales','number','must be in 10,000-unit steps'],['allocation','Trainer sales allocation','number','external assumption'],['market','Market investment','number','minimum Sh 1,000'],['milk','Milk purchased','number','tons'],['premise','Premise','select',Object.keys(premises)],['machine','Additional machine','machine',null],['loan','New loan received','number','Sh'],['term','Loan term','number','seasons'],['production','Planned production','number','units']
];
let state=structuredClone(defaults);
const fmt=n=>`Sh ${Math.round(n).toLocaleString()}`; const units=n=>Math.round(n).toLocaleString();
function renderFields(key){const root=document.getElementById(`fields-${key}`);root.innerHTML='';fieldDefs.forEach(([id,label,type,meta])=>{const wrap=document.createElement('div');wrap.className='field'+(id==='production'?' full':'');const lab=document.createElement('label');lab.textContent=label;wrap.append(lab);let el;if(type==='select'){el=document.createElement('select');meta.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=`Premise ${v} — rent ${fmt(premises[v].rent)}, transport ${premises[v].transport}/unit`;el.append(o)})}else if(type==='machine'){el=document.createElement('select');Object.entries(machines).forEach(([v,m])=>{const o=document.createElement('option');o.value=v;o.textContent=v==='none'?m.name:`${m.name} — ${units(m.capacity)} capacity / ${fmt(m.purchase)}`;el.append(o)})}else{el=document.createElement('input');el.type='number';el.step=id==='request'||id==='allocation'||id==='production'||id==='forecast'?'10000':'1'}el.value=state[key][id];el.dataset.key=key;el.dataset.id=id;el.addEventListener('input',e=>{state[key][id]=(type==='select'||type==='machine')?e.target.value:Number(e.target.value);update()});wrap.append(el);if(type==='number'&&meta){const sm=document.createElement('small');sm.textContent=meta;wrap.append(sm)}root.append(wrap)})}
function calc(s){const p=premises[s.premise],m=machines[s.machine];const capacity=BASE.existingCapacity+m.capacity;const milkCapacity=s.milk*BASE.milkOutput;const actualSales=Math.max(0,Math.min(s.allocation,s.request,s.production));const revenue=actualSales*BASE.salePrice;const spoilage=Math.max(0,s.production-actualSales);const milkExpense=s.milk*BASE.milkCost;const maint=BASE.existingMaintenance+m.maintenance;const depreciation=BASE.existingDepreciation+m.depreciation;const transport=actualSales*p.transport;const loanInterest=s.loan>0?s.loan*.10:0;const principal=s.loan>0&&s.term>0?s.loan/s.term:0;const pbt=revenue-milkExpense-maint-depreciation-transport-s.market-BASE.salary-p.rent-loanInterest;const tax=Math.max(0,pbt)*BASE.taxRate;const net=pbt-tax;const closeCash=BASE.openingCash+s.loan+revenue-m.purchase-milkExpense-maint-transport-s.market-BASE.salary-p.rent-loanInterest-principal-tax;return{capacity,milkCapacity,actualSales,revenue,spoilage,milkExpense,maint,depreciation,transport,loanInterest,principal,pbt,tax,net,closeCash,m,p,checks:{market:s.market>=1000,requestStep:s.request%10000===0,allocation:s.allocation<=s.request,capacity:s.production<=capacity,milk:s.production<=milkCapacity,debt:s.loan<=200000,cash:closeCash>=0}}}
function cls(n){return n>=0?'good':'bad'}
function row(label,a,b,formatter=fmt){return `<tr><td>${label}</td><td class="${typeof a==='number'?cls(a):''}">${formatter(a)}</td><td class="${typeof b==='number'?cls(b):''}">${formatter(b)}</td></tr>`}
function update(){const A=calc(state.a),B=calc(state.b);document.getElementById('comparison-body').innerHTML=
 row('Closing cash',A.closeCash,B.closeCash)+row('Winter net profit / loss',A.net,B.net)+row('Revenue',A.revenue,B.revenue)+row('Actual sales used',A.actualSales,B.actualSales,units)+row('Planned production',state.a.production,state.b.production,units)+row('Spoilage / unsold units',A.spoilage,B.spoilage,units)+row('Available machine capacity',A.capacity,B.capacity,units)+row('Loan principal repayment',A.principal,B.principal)+row('New machine cash cost',A.m.purchase,B.m.purchase);
 const betterCash=A.closeCash>B.closeCash?'Option A':'Option B';const lowerWaste=A.spoilage<B.spoilage?'Option A':A.spoilage>B.spoilage?'Option B':'Both options';document.getElementById('cash-insight').textContent=`${betterCash} produces the stronger Winter closing-cash result under the current assumptions. Both plans should still be judged against the negative Year 2 opening position of ${fmt(BASE.openingCash)}.`;document.getElementById('capacity-insight').textContent=`${lowerWaste} has the lower projected spoilage. Capacity is only useful if trainer allocation and demand are high enough to turn production into sales.`;
 const cg=document.getElementById('checks-grid');cg.innerHTML='';[['A',A],['B',B]].forEach(([name,r])=>{Object.entries({"Market investment ≥ Sh 1,000":r.checks.market,"Requested sales in 10,000 steps":r.checks.requestStep,"Allocation ≤ request":r.checks.allocation,"Production ≤ machine capacity":r.checks.capacity,"Production ≤ milk capacity":r.checks.milk,"Debt cap ≤ Sh 200,000":r.checks.debt,"Closing cash non-negative":r.checks.cash}).forEach(([label,ok])=>{const d=document.createElement('div');d.className='check';d.innerHTML=`<div><strong>Option ${name}</strong><br><span>${label}</span></div><span class="status ${ok?'ok':label.includes('cash')?'warning':'error'}">${ok?'CHECK':'WARNING'}</span>`;cg.append(d)})})}
function reset(k){state[k]=structuredClone(defaults[k]);renderFields(k);update()}
document.querySelectorAll('[data-reset]').forEach(b=>b.addEventListener('click',()=>reset(b.dataset.reset)));
document.getElementById('copy-summary').addEventListener('click',async()=>{const A=calc(state.a),B=calc(state.b);const txt=`Year 2 Winter scenario comparison\nOption A: closing cash ${fmt(A.closeCash)}, net result ${fmt(A.net)}, sales ${units(A.actualSales)}, spoilage ${units(A.spoilage)}.\nOption B: closing cash ${fmt(B.closeCash)}, net result ${fmt(B.net)}, sales ${units(B.actualSales)}, spoilage ${units(B.spoilage)}.\nKey uncertainty: trainer sales allocation is not guaranteed.`;try{await navigator.clipboard.writeText(txt);document.getElementById('copy-status').textContent='Copied.'}catch{document.getElementById('copy-status').textContent='Copy failed — select manually.'}});
renderFields('a');renderFields('b');update();
